review:
  # Installing review bot (danger) and plugins to it:
  stage: test
  image: ruby:2.3
  before_script:
    - gem install danger-gitlab danger-todoist
  script:
    - danger --fail-on-errors=true
  except:
    - master
    - schedules
