review:
  stage: test
  image: wemakeservices/kira-review:latest
  variables:
    # Set platforms that you are using for the project.
    # Example: "elixir,node"
    # See: https://github.com/wemake-services/kira-review
    DANGER_PLATFORMS: ""
  script:
    - danger --fail-on-errors=true --fail-if-no-pr=true
      --dangerfile=/danger/Dangerfile
  only:
    - merge_requests
