# HIGHLIGHT WITH A CLICKABLE LINK IF IMPORTANT FILES ARE CHANGED.
important_files = [
  "package.json",
  "tsconfig.json",
  ".eslintrc.js",
  "jest.config.js",
  ".nvmrc",
  "docker-compose.yml",
  "docker/node/Dockerfile",
  "config/.env.template",
]

important_files.each do |item|
  warn "#{gitlab.html_link(item)} was edited." if
    git.modified_files.include? item
end

# CODE CHANGES MUST ALSO BRING TEST CHANGES.
has_app_changes = !git.modified_files.grep(/src/).empty?
tests_updated = !git.modified_files.grep(/tests/).empty?
if has_app_changes && !tests_updated
  warn("The source code was changed, but the tests remained unmodified.
  Consider updating or adding to the tests to match the library changes.")
end
