# FAIL CI WHEN AN MR IS NOT CLASSIFIED AS WORK IN PROGRESS.
failure(
  "MR is not classified as Work in Progress.
  So why is it running inside the CI?
  See our policy about working with MRs",
  sticky: true
) unless gitlab.mr_json["work_in_progress"]

# ONLY ACCEPT MRS TO THE MASTER BRANCH.
failure "Please re-submit this MR to master branch. This one can be closed" if
  gitlab.branch_for_merge != "master"

# FAIL REALLY BIG DIFFS.
failure "We cannot handle the scale of this MR, split it" if
  git.lines_of_code > 5000

# FAIL WHEN GIT HAS MERGE COMMITS.
if git.commits.any? { |c| c.message =~ /^Merge branch/ }
  failure "Please rebase to get rid of the merge commits in this MR"
end
