# ONLY ACCEPT MRS TO THE MASTER BRANCH.
failure "Please re-submit this MR to master branch. This one can be closed" if
  gitlab.branch_for_merge != "master"

# FAIL REALLY BIG DIFFS.
failure "We cannot handle the scale of this MR, split it" if
  git.lines_of_code > 5000
