name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: docker build . --tag=wemake-services/kira-review

    - name: dry-run docker-based test
      run: |
        docker run \
          -v $PWD:/code \
          wemake-services/kira-review \
          danger dry_run --fail-on-errors=true --fail-if-no-pr=true --dangerfile=/danger/tests/Dangerfile

  deploy:
    if: "github.event_name == 'push' && github.repository == 'wemake-services/kira-review'"
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: wemakeservices/kira-release
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
